### ISSUE TITLE
关于docker镜像的问题

### ISSUE THREAD

**Issue by changhy666** [IvanaXu/TianChiProj#3]
作者你好，SecurityAI_Round5比赛README.pdf里面提到了docker环境依赖， 请问下面构建新镜像是用于支持训练环境，还是只是提交用？

**Comment by IvanaXu** [comment]
构建mmcv 训练用

**Comment by changhy666** [comment]
请问这个Dockerfile是最原始的吗？
我跑报错了，好像得在RUN apt-get update前面加下面这几个命令才能跑起来？
COPY sources.list /etc/apt/sources.list
COPY apt.conf /etc/apt/apt.conf
COPY https /usr/lib/apt/methods/https

**Comment by IvanaXu** [comment]
原始的
我猜是网络等引起的，理论上不需要
