### ISSUE TITLE
抗原抗体结合Epitope和Paratope精准确定

### ISSUE THREAD

**Issue by AYE0130** [IvanaXu/TianChiProj#32]
冒昧的问一下您关于这个赛题的问题，给的数据集只有fasta和PDB文件，并没有结合位点相关数据，如何能从分类的角度去考虑原子键能否成键呢?

**Comment by IvanaXu** [comment]
您要不着急的话 咱可以决赛后讨论这个问题

**Comment by AYE0130** [comment]
好的，可以问一下决赛什么时候结束吗？谢谢了

**Comment by AYE0130** [comment]
好的，感谢您的回复
