### ISSUE TITLE
关于SecurityAI_Round5的pth模型文件

### ISSUE THREAD

**Issue by changhy666** [IvanaXu/TianChiProj#4]
大佬你好，比赛用到的S499.pth和S488.pth没在项目文件中看到，是放到别处了吗？

**Comment by IvanaXu** [comment]
是的 有需要的话 可以给个链接

**Comment by changhy666** [comment]
感谢，可以发我这个邮箱吗？chy_666@163.com

**Comment by IvanaXu** [comment]
> https://ivan-bucket-out-001.oss-cn-beijing.aliyuncs.com/S477.pth
> https://ivan-bucket-out-001.oss-cn-beijing.aliyuncs.com/S488.pth
> https://ivan-bucket-out-001.oss-cn-beijing.aliyuncs.com/S499.pth

见上述下载链接，请尽快下载，后将下线
