### ISSUE TITLE
NEW 2023.11-1.APTOS2023

### ISSUE THREAD

**Issue by IvanaXu** [IvanaXu/TianChiProj#42]

**Comment by Easy-PB** [comment]
有APTOS2023相关代码吗

**Comment by Ho-Tung** [comment]
> 有APTOS2023相关代码吗

可参考原作者这篇：
[【ERNIE-5.0】多模态眼部疾病诊断AI助手EDA](https://aistudio.baidu.com/projectdetail/9952398?sUid=979775&shared=1&ts=1772425158993)
