### ISSUE TITLE
2019.11“数字人体”视觉挑战赛——宫颈癌风险智能诊断

### ISSUE THREAD

**Issue by cjjcn** [IvanaXu/TianChiProj#45]
请问您是否可以共享下`2019.11“数字人体”视觉挑战赛——宫颈癌风险智能诊断`的比赛baseline，我在官方比赛页面已经找不到代码了，万分感谢

**Comment by IvanaXu** [comment]
年代久远 暂时只整理这么多
貌似也没有baseline 但./2019.11-1.Cervical_Cancer/base 确是官方所附

**Comment by cjjcn** [comment]
> 年代久远 暂时只整理这么多 貌似也没有baseline 但./2019.11-1.Cervical_Cancer/base 确是官方所附

好的，非常感谢！
