### ISSUE TITLE
关于run.sh的问题

### ISSUE THREAD

**Issue by changhy666** [IvanaXu/TianChiProj#5]
大佬好，初次用docker环境不太懂，发现下面这个奇怪的问题。
在根路径或者code下，直接运行run.sh失败，如下图所示
![image](https://user-images.githubusercontent.com/57101883/185614909-f98095f4-fe55-49e8-889b-4ab4ca1a6bf0.png)
但是直接python code/test/result.py，就可以成功跑预测
![image](https://user-images.githubusercontent.com/57101883/185615372-8710fca6-5681-41bc-a794-597bd0f4e4be.png)

**Comment by IvanaXu** [comment]
其实一样的，目测是 相对路径的问题
