### ISSUE TITLE
关于生成的gt框问题

### ISSUE THREAD

**Issue by changhy666** [IvanaXu/TianChiProj#7]
用cv函数框选的mask外边界，貌似存在一些局部特别多极小框的问题，如下图所示。
![image](https://user-images.githubusercontent.com/57101883/188353680-c4147cfb-7f71-4ed7-a5c7-14ebd3cf78f9.png)
会带来几个问题：
1）gt框太多可能会导致CUDA memory Error；
2）太多小目标框，多loss的贡献可能不是很有效；

是不是可以从下面两个角度入手解决上面的问题：
1）如果小框被一个大框，完全包围，那么小框丢弃；
2）如果小框小到一定程度，也丢弃；

**Comment by IvanaXu** [comment]
u got the point 根据之前的经验，越小的修改是篡改模型越精细的体现
2）其实可行，阈值即取决于对抗的篡改模型的精细程度，简单数据分析就可以得到

**Comment by changhy666** [comment]
ps检测工程落地场景，出现太多小目标训练不太友好，我是这么做的，可以解决这个问题。
bbox_list = [list(cv2.boundingRect(i)) for i in contours]
# 丢弃极端框，极小框：像素面积过小，极端长宽比：大于100:1
bbox_list = [i for i in bbox_list if i[2] * i[3] > 90 and max(i[2:4]) / (min(i[2:4]) + 1e-5) < 100]

**Comment by IvanaXu** [comment]
good job 可以的 有评估对最终效果提升么

**Comment by changhy666** [comment]
没有在benchmark上细致评估，从训练过程的指标上看应该是有轻微提升的，之前的训练small target指标上很差。
